In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b = np.append(a, [10, 12])
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12])

In [5]:
c = np.random.randint(1, 99, size=24).reshape(2, 3, 4)
c

array([[[95, 36, 13, 93],
        [22, 76, 72, 38],
        [85,  9,  3, 21]],

       [[64, 20, 68, 78],
        [72, 72, 77, 46],
        [41, 80, 96, 67]]], dtype=int32)

In [24]:
g = np.random.randint(1, 99, size=24).reshape(2, 3, 4)
d = np.append(c, g, axis=0)
d


array([[[95, 36, 13, 93],
        [22, 76, 72, 38],
        [85,  9,  3, 21]],

       [[64, 20, 68, 78],
        [72, 72, 77, 46],
        [41, 80, 96, 67]],

       [[30, 54, 59, 92],
        [44, 23, 27, 17],
        [45, 58, 83, 26]],

       [[ 4, 65, 62, 22],
        [58, 58, 77, 17],
        [ 6, 26,  3, 49]]], dtype=int32)

In [10]:
g

array([[[13, 24, 11, 63],
        [20, 43, 95, 51],
        [17, 83, 91, 34]],

       [[21, 31, 44, 22],
        [75, 37, 49, 75],
        [91, 62, 30, 66]]], dtype=int32)

In [26]:
d.shape

(4, 3, 4)

In [36]:
h = np.insert(c, 3, [1, 2, 3], axis=2)
h

array([[[95, 36, 13,  1, 93],
        [22, 76, 72,  2, 38],
        [85,  9,  3,  3, 21]],

       [[64, 20, 68,  1, 78],
        [72, 72, 77,  2, 46],
        [41, 80, 96,  3, 67]]], dtype=int32)

In [37]:
v = np.empty((2, 3, 4))
v

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [38]:
np.copyto(v, c)
v

array([[[95., 36., 13., 93.],
        [22., 76., 72., 38.],
        [85.,  9.,  3., 21.]],

       [[64., 20., 68., 78.],
        [72., 72., 77., 46.],
        [41., 80., 96., 67.]]])

In [43]:
m = np.delete(c, 0, axis=0)
m

array([[[64, 20, 68, 78],
        [72, 72, 77, 46],
        [41, 80, 96, 67]]], dtype=int32)