In [1]:
import numpy as np

In [2]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [3]:
a.shape = (2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [4]:
b = a.reshape((2, 12))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [5]:
b[0, 0] = 77
b

array([[77,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [6]:
a

array([[[77,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [7]:
b is a

False

In [8]:
ravel_a = np.ravel(a)
ravel_a

array([77,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [9]:
flatten_a = a.flatten()
flatten_a

array([77,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [10]:
flatten_a is a

False

In [11]:
ravel_a is a

False

In [12]:
flatten_a[2] = 300
flatten_a

array([ 77,   1, 300,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [13]:
ravel_a[1] = 200
ravel_a

array([ 77, 200,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [14]:
a

array([[[ 77, 200,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [15]:
flat_a = list(a.flat)
flat_a[:7]

[np.int64(77),
 np.int64(200),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6)]

In [16]:
my_3D_array = np.arange(24).reshape((2, 3, 4))
my_3D_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [17]:
np.fliplr(a)

array([[[  8,   9,  10,  11],
        [  4,   5,   6,   7],
        [ 77, 200,   2,   3]],

       [[ 20,  21,  22,  23],
        [ 16,  17,  18,  19],
        [ 12,  13,  14,  15]]])

In [18]:
np.fliplr(my_3D_array)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [19]:
np.flipud(a)

array([[[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[ 77, 200,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]]])

In [20]:
np.flipud(my_3D_array)

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [21]:
a

array([[[ 77, 200,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [22]:
my_3D_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [24]:
np.roll(b, 2)

array([[ 22,  23,  77, 200,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21]])

In [25]:
b

array([[ 77, 200,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]])

In [26]:
np.roll(a, 2)

array([[[ 22,  23,  77, 200],
        [  2,   3,   4,   5],
        [  6,   7,   8,   9]],

       [[ 10,  11,  12,  13],
        [ 14,  15,  16,  17],
        [ 18,  19,  20,  21]]])

In [27]:
np.rot90(b)

array([[ 11,  23],
       [ 10,  22],
       [  9,  21],
       [  8,  20],
       [  7,  19],
       [  6,  18],
       [  5,  17],
       [  4,  16],
       [  3,  15],
       [  2,  14],
       [200,  13],
       [ 77,  12]])

In [28]:
np.rot90(my_3D_array)

array([[[ 8,  9, 10, 11],
        [20, 21, 22, 23]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 0,  1,  2,  3],
        [12, 13, 14, 15]]])

In [ ]:
np.rot90(b, k=-1)