In [1]:
import numpy as np

In [2]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
a + 4

array([4, 5, 6, 7, 8])

In [4]:
b = np.random.randint(1, 9, size=50).reshape((5, 10))
b

array([[2, 1, 4, 6, 4, 8, 7, 3, 8, 5],
       [2, 6, 7, 8, 8, 3, 8, 6, 2, 2],
       [6, 2, 7, 8, 7, 2, 3, 2, 5, 8],
       [3, 3, 7, 1, 5, 6, 2, 8, 1, 4],
       [6, 7, 3, 3, 3, 6, 3, 5, 6, 6]], dtype=int32)

In [7]:
c = np.random.randint(1, 99, size=50).reshape((5, 10))
c

array([[58, 18,  4, 56, 24, 82, 83, 29, 97, 31],
       [74, 60, 58, 33,  6, 37, 93, 72, 64, 97],
       [65, 95, 17, 25, 92, 33, 98, 49, 27, 60],
       [34, 49, 28, 19, 26, 95, 37, 15, 38, 47],
       [89, 49, 72, 92, 47, 22, 13, 53, 96, 35]], dtype=int32)

In [9]:
c * b

array([[116,  18,  16, 336,  96, 656, 581,  87, 776, 155],
       [148, 360, 406, 264,  48, 111, 744, 432, 128, 194],
       [390, 190, 119, 200, 644,  66, 294,  98, 135, 480],
       [102, 147, 196,  19, 130, 570,  74, 120,  38, 188],
       [534, 343, 216, 276, 141, 132,  39, 265, 576, 210]], dtype=int32)

In [12]:
array1 = np.random.randint(1, 10, size=60).reshape((2, 3, 10))
array1

array([[[2, 5, 8, 9, 2, 1, 1, 6, 2, 1],
        [9, 3, 7, 5, 3, 5, 9, 3, 4, 4],
        [8, 1, 8, 3, 4, 1, 7, 8, 9, 3]],

       [[6, 8, 6, 4, 1, 1, 3, 9, 1, 7],
        [2, 8, 5, 9, 2, 7, 9, 9, 6, 7],
        [7, 6, 7, 6, 4, 8, 1, 3, 3, 3]]], dtype=int32)

In [14]:
array2 = np.random.randint(1, 10, size=10).reshape((1, 10))
array2

array([[8, 3, 8, 1, 2, 2, 3, 6, 4, 9]], dtype=int32)

In [18]:
f = array1 - array2
f

array([[[-6,  2,  0,  8,  0, -1, -2,  0, -2, -8],
        [ 1,  0, -1,  4,  1,  3,  6, -3,  0, -5],
        [ 0, -2,  0,  2,  2, -1,  4,  2,  5, -6]],

       [[-2,  5, -2,  3, -1, -1,  0,  3, -3, -2],
        [-6,  5, -3,  8,  0,  5,  6,  3,  2, -2],
        [-1,  3, -1,  5,  2,  6, -2, -3, -1, -6]]], dtype=int32)

In [23]:
np.mean(f)

np.float64(0.38333333333333336)

In [25]:
np.median(array1)

np.float64(5.0)

In [30]:
test_array = np.random.randint(1, 100, size=10000000)
test_array[:14]

array([63, 25, 36, 36, 27, 38, 13,  5, 98, 95, 55, 71, 21, 24],
      dtype=int32)

In [31]:
import datetime

python_start = datetime.datetime.now()
python_result = sum(test_array)
python_end = datetime.datetime.now()
python_time = python_end - python_start
python_time

datetime.timedelta(seconds=1, microseconds=954987)

In [32]:
import datetime

np_start = datetime.datetime.now()
np_result = np.sum(test_array)
np_end = datetime.datetime.now()
np_time = np_end - np_start
np_time

datetime.timedelta(microseconds=25640)

In [33]:
python_time / np_time

76.24754290171607