In [1]:
import numpy as np

In [2]:
a = np.random.randint(0, 99, size=(3, 4))
b = np.random.randint(0, 99, size=(3, 4))
a, b

(array([[93, 14, 54, 87],
        [77, 92,  7, 15],
        [84,  2, 74, 96]], dtype=int32),
 array([[ 7,  9, 60, 73],
        [26, 61, 10, 58],
        [47,  7, 34, 22]], dtype=int32))

In [3]:
a * b

array([[ 651,  126, 3240, 6351],
       [2002, 5612,   70,  870],
       [3948,   14, 2516, 2112]], dtype=int32)

In [4]:
c = np.random.randint(0, 99, size=(4, 3))

In [6]:
d = np.dot(a, c)
d

array([[ 7420, 11366, 12524],
       [ 8189, 10590, 10343],
       [ 8148, 11850, 13210]], dtype=int32)

In [7]:
e = np.dot(a, b.T)
e

array([[10368,  8858,  8219],
       [ 2882,  8554,  4831],
       [12054,  8614,  8590]], dtype=int32)