In [1]:
import numpy as np

In [2]:
a = np.arange(1, 13).reshape(3, 4)
b = np.arange(13, 25).reshape(3, 4)


In [3]:
result0 = np.concatenate((a, b), axis=0)
result0

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [4]:
result1 = np.concatenate((a, b), axis=1)
result1

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [5]:
stack0 = np.stack((a, b), axis=0)
stack1 = np.stack((a, b), axis=1)
stack2 = np.stack((a, b), axis=2)

In [6]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
b

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [8]:
stack0

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [9]:
stack1

array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [10]:
stack2

array([[[ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16]],

       [[ 5, 17],
        [ 6, 18],
        [ 7, 19],
        [ 8, 20]],

       [[ 9, 21],
        [10, 22],
        [11, 23],
        [12, 24]]])

In [11]:
c = np.random.randint(1, 100, size=40).reshape(4, 2, 5)
c

array([[[33,  9, 40, 80,  8],
        [78, 53, 19, 88, 46]],

       [[99, 23, 73, 55, 53],
        [72, 77, 70, 68, 43]],

       [[ 2, 97, 72, 66, 43],
        [27, 63, 91, 96, 28]],

       [[58, 29, 99, 47,  2],
        [44, 74, 25,  1, 67]]], dtype=int32)

In [12]:
c.shape

(4, 2, 5)

In [39]:
split0 = np.split(c, 4, axis=0)
split1 = np.split(c, 2, axis=1)
split2 = np.split(c, 5, axis=2)
c

array([[[33,  9, 40, 80,  8],
        [78, 53, 19, 88, 46]],

       [[99, 23, 73, 55, 53],
        [72, 77, 70, 68, 43]],

       [[ 2, 97, 72, 66, 43],
        [27, 63, 91, 96, 28]],

       [[58, 29, 99, 47,  2],
        [44, 74, 25,  1, 67]]], dtype=int32)

In [41]:
split0

[array([[[33,  9, 40, 80,  8],
         [78, 53, 19, 88, 46]]], dtype=int32),
 array([[[99, 23, 73, 55, 53],
         [72, 77, 70, 68, 43]]], dtype=int32),
 array([[[ 2, 97, 72, 66, 43],
         [27, 63, 91, 96, 28]]], dtype=int32),
 array([[[58, 29, 99, 47,  2],
         [44, 74, 25,  1, 67]]], dtype=int32)]