In [1]:
import numpy as np

In [3]:
a = np.mod(10, 2)
a

np.int64(0)

In [4]:
b = np.equal(2, 2)
b

np.False_

In [5]:
def is_integer(number):
    return np.equal(np.mod(number, 1), 0)

In [6]:
np_func = np.frompyfunc(is_integer, 1, 1)

In [7]:
numbers_range = 9

In [8]:
frist_array = np.arange(numbers_range) + 1
second_array = np.arange(numbers_range) + 1
frist_array, second_array

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [9]:
result = np.add.outer(frist_array ** 2, second_array ** 2)
result

array([[  2,   5,  10,  17,  26,  37,  50,  65,  82],
       [  5,   8,  13,  20,  29,  40,  53,  68,  85],
       [ 10,  13,  18,  25,  34,  45,  58,  73,  90],
       [ 17,  20,  25,  32,  41,  52,  65,  80,  97],
       [ 26,  29,  34,  41,  50,  61,  74,  89, 106],
       [ 37,  40,  45,  52,  61,  72,  85, 100, 117],
       [ 50,  53,  58,  65,  74,  85,  98, 113, 130],
       [ 65,  68,  73,  80,  89, 100, 113, 128, 145],
       [ 82,  85,  90,  97, 106, 117, 130, 145, 162]])

In [10]:
final = np.sqrt(result)
final

array([[ 1.41421356,  2.23606798,  3.16227766,  4.12310563,  5.09901951,
         6.08276253,  7.07106781,  8.06225775,  9.05538514],
       [ 2.23606798,  2.82842712,  3.60555128,  4.47213595,  5.38516481,
         6.32455532,  7.28010989,  8.24621125,  9.21954446],
       [ 3.16227766,  3.60555128,  4.24264069,  5.        ,  5.83095189,
         6.70820393,  7.61577311,  8.54400375,  9.48683298],
       [ 4.12310563,  4.47213595,  5.        ,  5.65685425,  6.40312424,
         7.21110255,  8.06225775,  8.94427191,  9.8488578 ],
       [ 5.09901951,  5.38516481,  5.83095189,  6.40312424,  7.07106781,
         7.81024968,  8.60232527,  9.43398113, 10.29563014],
       [ 6.08276253,  6.32455532,  6.70820393,  7.21110255,  7.81024968,
         8.48528137,  9.21954446, 10.        , 10.81665383],
       [ 7.07106781,  7.28010989,  7.61577311,  8.06225775,  8.60232527,
         9.21954446,  9.89949494, 10.63014581, 11.40175425],
       [ 8.06225775,  8.24621125,  8.54400375,  8.94427191,  9

In [11]:
np_func(final)

array([[np.False_, np.False_, np.False_, np.False_, np.False_, np.False_,
        np.False_, np.False_, np.False_],
       [np.False_, np.False_, np.False_, np.False_, np.False_, np.False_,
        np.False_, np.False_, np.False_],
       [np.False_, np.False_, np.False_, np.True_, np.False_, np.False_,
        np.False_, np.False_, np.False_],
       [np.False_, np.False_, np.True_, np.False_, np.False_, np.False_,
        np.False_, np.False_, np.False_],
       [np.False_, np.False_, np.False_, np.False_, np.False_, np.False_,
        np.False_, np.False_, np.False_],
       [np.False_, np.False_, np.False_, np.False_, np.False_, np.False_,
        np.False_, np.True_, np.False_],
       [np.False_, np.False_, np.False_, np.False_, np.False_, np.False_,
        np.False_, np.False_, np.False_],
       [np.False_, np.False_, np.False_, np.False_, np.False_, np.True_,
        np.False_, np.False_, np.False_],
       [np.False_, np.False_, np.False_, np.False_, np.False_, np.False_,
  