In [1]:
import numpy as np

In [2]:
a = np.arange(10)
b = np.arange(12).reshape((3, 4))

In [4]:
np.tile(a, 3).reshape(3, a.size)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [5]:
np.tile(a, (2, 2))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [6]:
np.tile(a, (2, 2, 2))

array([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [7]:
np.repeat(a, 2)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9])

In [8]:
np.repeat(b, 2)

array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
        8,  9,  9, 10, 10, 11, 11])

In [11]:
np.repeat(b, 2, axis=1)

array([[ 0,  0,  1,  1,  2,  2,  3,  3],
       [ 4,  4,  5,  5,  6,  6,  7,  7],
       [ 8,  8,  9,  9, 10, 10, 11, 11]])

In [12]:
c = np.random.randint(99, size=10)
d = np.random.randint(99, size=(3, 4))

In [13]:
np.sort(c)

array([14, 30, 33, 43, 60, 68, 73, 76, 81, 94], dtype=int32)

In [15]:
np.sort(d)

array([[ 4, 43, 50, 77],
       [12, 55, 61, 69],
       [ 7, 42, 87, 89]], dtype=int32)

In [16]:
np.sort(d, axis=0)

array([[ 7, 50,  4, 12],
       [43, 69, 42, 77],
       [55, 87, 61, 89]], dtype=int32)

In [17]:
np.argsort(c)

array([9, 4, 8, 1, 7, 5, 3, 2, 0, 6])

In [18]:
np.argsort(d)

array([[2, 0, 1, 3],
       [3, 0, 2, 1],
       [0, 2, 1, 3]])

In [20]:
np.argsort(d, axis=0)

array([[2, 0, 0, 1],
       [0, 1, 2, 0],
       [1, 2, 1, 2]])

In [21]:
np.argmax(c)

np.int64(6)

In [22]:
d

array([[43, 50,  4, 77],
       [55, 69, 61, 12],
       [ 7, 87, 42, 89]], dtype=int32)

In [ ]:
np.argmax