In [1]:
import numpy as np

In [2]:
my_vector = np.arange(6)
my_2D_array = np.arange(12).reshape((3, 4))
my_3D_array = np.arange(24).reshape((2, 3, 4))

In [3]:
my_vector.shape

(6,)

In [5]:
my_vector

array([0, 1, 2, 3, 4, 5])

In [6]:
np.transpose(my_vector)

array([0, 1, 2, 3, 4, 5])

In [7]:
my_vector.shape = (1, 6)

In [8]:
my_vector

array([[0, 1, 2, 3, 4, 5]])

In [9]:
np.transpose(my_vector)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [11]:
my_2D_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
np.transpose(my_2D_array)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [14]:
after_transpose = np.transpose(my_3D_array, axes=(0, 1, 2))
after_transpose

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
my_3D_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
my_3D_array.shape, after_transpose.shape

((2, 3, 4), (2, 3, 4))

In [18]:
after_transpose = np.transpose(my_3D_array, axes=(0, 2, 1))
my_3D_array.shape, after_transpose.shape

((2, 3, 4), (2, 4, 3))

In [22]:
np.swapaxes(my_3D_array, 1,2).shape

(2, 4, 3)

In [23]:
np.moveaxis(my_3D_array, 2, 0).shape

(4, 2, 3)