In [1]:
import numpy as np

In [3]:
a = np.arange(16, 25)
a

array([16, 17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
a[0]


np.int64(16)

In [8]:
b = np.arange(1, 21)
b.shape = (4, 5)
b
b[1][-1]

np.int64(10)

In [9]:
b[:, :2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [13]:
e = np.random.randint(1, 9, size=(2, 3, 4))
e[:, :, -2:]


array([[[7, 4],
        [2, 1],
        [4, 4]],

       [[2, 8],
        [4, 8],
        [4, 4]]], dtype=int32)