In [1]:
import numpy as np

In [3]:
a = np.arange(0, 21, 2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
a = np.linspace(0, 20, 5)
a

array([ 0.,  5., 10., 15., 20.])

In [6]:
c = np.ones((3, 3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
b = np.zeros((3, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
e = np.random.random(size=(3, 4))
e
f = np.random.randint(1, 10, (3, 3))
f

array([[8, 7, 2],
       [1, 2, 9],
       [9, 4, 9]], dtype=int32)

In [20]:
np.random.seed(1)
t = np.random.randint(1, 11, (3, 3))
t

array([[ 6,  9, 10],
       [ 6,  1,  1],
       [ 2,  8,  7]], dtype=int32)