In [4]:
import numpy as np

In [5]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [6]:
a.shape


(3,)

In [7]:
a.ndim

1

In [8]:
a.dtype

dtype('int64')

In [9]:
a.size

3

In [11]:
b = np.array([[1, 2, 3], [9, 7, 6]])
b

array([[1, 2, 3],
       [9, 7, 6]])

In [12]:
b.shape

(2, 3)

In [13]:
b.ndim


2

In [14]:
b.size

6

In [17]:
b = np.array([[1, 2, 3], [9, 7, 6]])
a = np.array([[1, 2, 3], [12, 67, 9]])
c = np.array([a, b])
c

array([[[ 1,  2,  3],
        [12, 67,  9]],

       [[ 1,  2,  3],
        [ 9,  7,  6]]])

In [18]:
c.shape


(2, 2, 3)

In [19]:
c.dtype


dtype('int64')

In [20]:
c.ndim


3

In [21]:
c.ndim

3

In [22]:
type(c)

numpy.ndarray