In [1]:
import numpy as np

In [2]:
a = np.random.randint(1, 100, size=(2, 3, 3))
a

array([[[38, 24, 85],
        [67, 14, 82],
        [97, 95, 87]],

       [[64,  5, 51],
        [16, 95, 94],
        [22, 49,  5]]], dtype=int32)

In [4]:
unique_array = np.unique(a)
unique_array

array([ 5, 14, 16, 22, 24, 38, 49, 51, 64, 67, 82, 85, 87, 94, 95, 97],
      dtype=int32)

In [5]:
a[a > 30]

array([38, 85, 67, 82, 97, 95, 87, 64, 51, 95, 94, 49], dtype=int32)

In [7]:
greater_than_30 = a > 30
greater_than_30

array([[[ True, False,  True],
        [ True, False,  True],
        [ True,  True,  True]],

       [[ True, False,  True],
        [False,  True,  True],
        [False,  True, False]]])

In [9]:
even_elements = a % 2 == 0
even_elements

array([[[ True,  True, False],
        [False,  True,  True],
        [False, False, False]],

       [[ True, False, False],
        [ True, False,  True],
        [ True, False, False]]])

In [12]:
final_mask = np.logical_and(greater_than_30, even_elements)
final_mask

array([[[ True, False, False],
        [False, False,  True],
        [False, False, False]],

       [[ True, False, False],
        [False, False,  True],
        [False, False, False]]])

In [13]:
a[final_mask]

array([38, 82, 64, 94], dtype=int32)