In [1]:
import numpy as np

In [7]:
frist_array = np.arange(1, 25).reshape(2, 3, 4)
frist_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [14]:
second_array = frist_array
frist_array is second_array

True

In [15]:
id(second_array), id(frist_array)

(2428294242512, 2428294242512)

In [17]:
third_array = frist_array.view()
frist_array is third_array

False

In [18]:
id(frist_array), id(third_array)

(2428294242512, 2428295134832)

In [19]:
third_array[0, 0, 0] = 100
third_array

array([[[100,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 13,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [20]:
frist_array

array([[[100,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 13,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [21]:
forth_array = np.copy(frist_array)
forth_array

array([[[100,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 13,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [22]:
forth_array[0, 0, 0] = 2000
forth_array

array([[[2000,    2,    3,    4],
        [   5,    6,    7,    8],
        [   9,   10,   11,   12]],

       [[  13,   14,   15,   16],
        [  17,   18,   19,   20],
        [  21,   22,   23,   24]]])

In [23]:
frist_array

array([[[100,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 13,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])